### PR TITLE
Immutable get-form

### PR DESCRIPTION
**Pull request by erin-doyle**
Modified get-form to use the immutable strategy and added it to the strategy used by all other consumers per #319.

Once this is merged I think (hope) #319 may be considered fixed.

### CODE REVIEW

**Comment by davidkpiano** [comment]
Thanks! One question - is the use of `redux-immutable` assumed/required by developers using `Immutable.JS` with this?

**Comment by erin-doyle** [comment]
No, my intention was that developers using `react-redux-form` should not be forced to use `redux-immutable` even when using `Immutable.JS`.  I only added `redux-immutable` to the dev-dependencies so we could use it in the examples.  The goal is that `react-redux-form` be compatible for use with or without `redux-immutable`.

**Comment by davidkpiano** [comment]
Gotcha, sounds good. By the way, I gave you collaborator access in case you ever need to make quick patches. Thanks so much for all your hard work on this!

**Comment by erin-doyle** [comment]
Thank you!  It was my pleasure!  This is a great library and I'm happy to contribute to it to push it forward in acceptance in the community. :)

**Comment by dmitrif** [comment]
@erin-doyle 

Working on PR now, but hoping you could chime in.

Seemingly while using redux-immutable / redux-immutablejs, the code contained in form-reducer / form-action-reducer, update-field, all do not use anything but the default `get` which fails. Did you have a chance to look into that prior?

Thanks!

**Pull request merged**
