### PR TITLE
Allow to pass custom component into <Form>

### PR DESCRIPTION
**Pull request by asvetliakov**
Same as for ```<Field/>```
My use case is need to use custom Form from UI lib

### CODE REVIEW

**Comment by davidkpiano** [comment]
Looks good! The only thing I'm worried about is that this can, in some cases, make `onSubmit` not behave as expected if the custom component doesn't implement `onSubmit`.

Then again, RRF isn't supposed to make assumptions :stuck_out_tongue_winking_eye:

**Comment by asvetliakov** [comment]
Can you make patch release with it?

**Comment by davidkpiano** [comment]
Sure, check back again in an hour

**Comment by davidkpiano** [comment]
Should be available now in `react-redux-form@0.10.2`!

**Comment by asvetliakov** [comment]
Thank you very much!

**Pull request merged**
