### PR TITLE
Immutable.JS Compatibility

### PR DESCRIPTION
**Pull request by dmitrif**
Previous Immutable JS support was not functioning properly, and was using Icepick structures under the hood. This PR uses Immutable under-the-hood and passes all unit tests as expected.

Sorry for the lackluster commit names, should've squashed prior to the first rebase, but should be able to squash during merging.

### CODE REVIEW

**Comment by dmitrif** [comment]
Not sure how to get around `lodash.toPath` imports failing, any ideas?

**Comment by davidkpiano** [comment]
Does `lodash.toPath` not work? The package depends only on `lodash.get` and `lodash.toPath`, so it should not depend on lodash as a whole.

**Comment by dmitrif** [comment]
Ah I see the issue. Patch coming in 5.

**Comment by dmitrif** [comment]
I updated the dependencies to explicitly rely on the lodash submodules that are in use, but the unit-tests are still failing on Travis due to the devDependency `lodash` failing to load.

**Comment by dmitrif** [comment]
@davidkpiano Sorry, any ideas? I want to make sure that this PR doesn't diverge too far from master, since it's a pain to get them back into sync (from my past experience).

**Comment by davidkpiano** [comment]
Sorry, my main concern with this PR is the number of calls for `.toJS`, which sorta defeats the purpose of Immutable.JS.

**Comment by dmitrif** [comment]
That's fair. The conversions happen due to the time constraint as I am unable to commit much more time to it — The logic that relies on toJS would have to be rewritten to accommodate both the immutable / regular branching. 

Unsure how to proceed.

**Comment by davidkpiano** [comment]
Closing this until we can figure out how to do this without `.toJS` calls, sorry 😢

**Comment by dmitrif** [comment]
I feel like in some places the calls are justified, in order to reduce the complexity of forking code into branches along the way to support both immutable and icepick. We can always identify the spots we feel are inappropriate for toJS and I can refactor accordingly.

I do feel it's best to move forward quickly (let me know if you agree), otherwise this PR will fall out of sync fairly quickly with the new updates and will be fairly useless.

**Comment by davidkpiano** [comment]
Sure, I'd be glad to continue discussion. Let's merge master into this and see what we can do to reduce the number of `.toJS` calls.

**Comment by dmitrif** [comment]
Hi, David. I just attempted a merge, and the problem that I foresaw with letting this pull stagnate is already exhibiting itself. There has been a number of changes to a variety of submodules resulting in a series of conflicts — without having an intimate knowledge of the library it will be tough for me to determine how to resolve these conflicts, primarily relying on the unit testing to tell me whether I am doing so correctly.

Is there any chance you could complete the merge of master?

**Comment by davidkpiano** [comment]
Sure, I'll do that soon.

**Comment by dmitrif** [comment]
Appreciate it. Thank you in advance :)

**Comment by dmitrif** [comment]
Did you get a chance to look at this?

**Comment by davidkpiano** [comment]
Right now, the merge is really complex - lots of things have changed internally. I think it would be best if this were done in a way that allowed for the form state to remain a JavaScript object instead of an Immutable.JS object. Otherwise, RRF is going to get really, really complex. 😟 

How would you deal with Immutable.JS with other APIs/libraries that don't use Immutable.JS? I'd want to approach RRF the same way. I personally don't use Immutable.JS because I think its benefits are overstated and its buy-in is too expensive for most non-trivial projects.

**Comment by dmitrif** [comment]
So the main issue with the Immutable compatibility in this, is if the redux state is an immutable object, the traversal / selecting substates becomes problematic as the react-redux-form is also stored in the store. 

The easiest way would possibly be creating a separate store for React-redux-form?

**Comment by davidkpiano** [comment]
> The easiest way would possibly be creating a separate store for React-redux-form?

I've had that thought - it makes sense but I'm worried about having two separate sources of truth. Have you seen similar projects do this? Would love to explore this for V2, would make many things much simpler.

**Comment by dmitrif** [comment]
Closing as it's been a few years and I am no longer actively working on the codebase. Thank you!

**Pull request closed without merging**
