### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by chrisblossom**
Sorry for the massive PR... probably easier to look at each commit instead.

Looks bigger than is because I added lib/ to gitignore so a lot of files are being removed from github.

See commit messages for detailed changes

### CODE REVIEW

**Comment by chrisblossom** [comment]
@davidkpiano I just merged eslint the changes listed above. Let me know your thoughts on this PR when you get sometime.

**Comment by davidkpiano** [comment]
@chrisblossom Would you mind taking a look at the Travis CI build error?

```
/home/travis/build/davidkpiano/react-redux-form/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
```

Fails on 2 of the 3 machines. Awesome progress on this so far by the way! Will run it locally and merge it in soon when all the tests pass.

**Comment by chrisblossom** [comment]
@davidkpiano There was a problem with travis-ci downloading node 4 as specified in the .travis config file. Can you re-run the tests through travis? Doesn't look like I am able to.

**Comment by davidkpiano** [comment]
Reran the tests! Looks good to merge, much thanks!

**Pull request merged**
