### PR TITLE
Fixing performance issues

### PR DESCRIPTION
**Pull request by davidkpiano**
@etrepum This PR moves the prop mapping to the internal `<Control>` state, which prevents it from recreating the mapped props _unless_ the field/control is supposed to rerender, anyway.

### CODE REVIEW

**Comment by etrepum** [comment]
I've tried adding this version as a dependency and it doesn't appear to fix the performance problem, I'm still seeing the same behavior inside my components (control, controlProps, onFocus, onBlur, onChange, onLoad, onSubmit changing for every component on every redux store update). I'll dig deeper later today.

**Comment by etrepum** [comment]
I can't seem to reproduce the problem in isolation with this PR, it definitely seems like an improvement :+1: Not sure why we're still having problems, but it could be on our end or perhaps there was some pollution in node_modules when I tried to pull it commit from git into our app. I don't see a reason not to merge this as-is.

**Comment by etrepum** [comment]
Thanks!

**Comment by davidkpiano** [comment]
Yep! There's more wins to be had, but this is a good start.

**Pull request merged**
