### PR TITLE
Add styled-components support in <Field />

### PR DESCRIPTION
**Pull request by asfktz**
Hi!
First of all, thank you for the work you put into this library 🙏

I made a small change to the `<Field />` component, to add support for styled-components

[styled-components](https://github.com/styled-components/styled-components) is a popular choice for styling components.

I also made a small snippet of code for you to test:

```js
import { Field, form } from 'react-redux-form';
import { connect } from 'react-redux';
import React, { Component } from 'react';
import styled from 'styled-components';

let MyInput = styled.input`
  border: 1px solid #DDD;
  padding: 10px;
  width: 100%;
  border-radius: 2px;
`

class LoginPage extends Component {
  render () {
    return (
      <div>
        <form>
          <Field model="login.username">
            <MyInput type="text" />
          </Field>
        </form>
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    login: state.forms.login
  }
}

export default connect(mapStateToProps)(LoginPage)
```

Wish you all good 😊
Asaf

### CODE REVIEW

**Comment by davidkpiano** [comment]
Does `styled-components` not work without this? If so, why not? Just curious.

**Comment by asfktz** [comment]
Good questions.
seems like it has something to do with HOCs, where a function wraps the original input component.

I tried to find a way to get the original component name out of a wrapped one, but it seems like its not available.

On the other hand, styled-components adds a `target` property on their wrapper component, 
so we can use it to our advantage.

I agree that it feels awkward to add a specific check for another library,
but I couldn't find a more generic solution to offer 🙁

```jsx
import React from 'react';
import styled from 'styled-components';

const WrappedInput = (props) => {
  return <input type="text" { ...props } />
}

const wrappedInput = <WrappedInput />

console.log(wrappedInput.type)              // returns: function WrappedInput(props) { ... }
console.log(wrappedInput.type.target)       // returns: undefined
console.log(wrappedInput.type.name)         // returns: WrappedInput
console.log(wrappedInput.type.displayName)  // returns: undefined


const StyledInput = styled.input`
  background: red;
`
const styledInput = <StyledInput />

console.log(styledInput.type)               // returns: function StyledComponent() { ... }
console.log(styledInput.type.target)        // returns: input
console.log(styledInput.type.name)          // returns: StyledComponent
console.log(styledInput.type.displayName)   // returns: styled.input
```

**Comment by prime-ralph** [comment]
I have managed to get around this by making custom controls: create a control styled with `styled-components`, then pass it to the `Control` as the `component` attribute.

**Comment by ralphstodomingo** [comment]
I've been using `styled-components` and `react-redux-form` with both `antd` and `material-ui`, and can safely say this is not really needed.

**Pull request closed without merging**
